# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 6"  # scheduled at 06:00 (UTC+8) every sunday
    # NY city in UTC-5 will be 22pm
    # London in UTC will be 3am
    # Beijing in UTC+8 will be 11am （Aus at 12am）
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    # Just to test run command‘s action， will delete martix in final version of release.yml
    
    steps:
    
    - name: Init
      uses: actions/checkout@v2
    
    - name: Run dist and wikidata with node${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run dist
    #- run: npm run wikidata
    
#     - name: commit
#       run: |
#         git config --global user.email keaitianxinmail@qq.com
#         git config --global user.name LaoshuBaby
#         cd dist && git init && git add .
#         git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')" -a	
#     - name: Push changes
#       uses: ad-m/github-push-action@main
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}

#     - name: Update dist folder to repository
#       env:
#         # GitHub Token
#         GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
#       run: |
#         git config --global init.defaultBranch "main"
#         git config --global user.email "keaitianxinmail@qq.com"
#         git config --global user.name "LaoshuBaby"
#         cd dist && git init && git add .
#         git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
#         git push --force --quiet "https://$GITHUB_TOKEN@github.com/LaoshuBaby/name-suggestion-index.git" main:main
#         echo $GITHUB_TOKEN

