# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release

on:
  schedule:
    - cron: "0 3 * * *"  # scheduled at 06:00 (UTC+8) everyday
    # NY city in UTC-5 will be 22pm
    # London in UTC will be 3am
    # Beijing in UTC+8 will be 11am （Aus at 12am）
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run dist
    - run: npm run wikidata


    - name: Update dist folder to repository
      env:
        # 仓库用户名
        REPO_USERNAME: "LaoshuBaby"
        # GitHub Pages仓库名
        DIST_REPO: "name-suggestion-index"
        # GitHub Token
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        git config --global user.email "Action@GitHub.com"
        git config --global user.name "GitHub Action"
        cd dist && git init && git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://$GITHUB_TOKEN@github.com/$REPO_USERNAME/$DIST_REPO.git" master:master
