# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 6"  # scheduled at 06:00 (UTC+8) every sunday
    # NY city in UTC-5 will be 22pm
    # London in UTC will be 3am
    # Beijing in UTC+8 will be 11am （Aus at 12am）
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    
    - name: Init
      uses: actions/checkout@v2
    
    - name: Run dist and wikidata
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm run dist
    - run: npm run wikidata

    - name: Update dist folder to repository
      env:
        REPO_USERNAME: "LaoshuBaby" # 仓库用户名
        DIST_REPO: "name-suggestion-index" # GitHub Pages仓库名
        # GitHub Token
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        git config --global user.email "Action@GitHub.com"
        git config --global user.name "GitHub Action"
        cd dist && git init && git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://$GITHUB_TOKEN@github.com/$REPO_USERNAME/$DIST_REPO.git" main:main
